# Generated by Django 3.2.13 on 2022-07-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220704_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='genre',
        ),
    ]
