# Generated by Django 3.2.13 on 2022-07-15 16:29

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
