# Generated by Django 3.2.13 on 2022-07-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
